import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { getCurrentEnvironment } from '@/lib/relay/environment';

const inter = Inter({ subsets: ['latin'] });

import RelayProvider from './relay-provider';

export const metadata: Metadata = {
  title: 'WordPress Headless com Next.js',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const environment = getCurrentEnvironment();

  return (
    <html lang="pt-br">
      <body className={inter.className} suppressHydrationWarning={true}>
        <RelayProvider>{children}</RelayProvider>
      </body>
    </html>
  );
}
